### ISSUE TITLE
I'm looking forward to adding looks="5x1" in submit_insar_job()

### ISSUE THREAD

**Issue by ZGHHGZ** [ASFHyP3/hyp3-gamma#461] opened 2023-05-12 00:56 UTC
I'm looking forward to adding looks="5x1" in submit_insar_job()

**Comment by jtherrmann** [comment] 2023-07-26 23:01
Closed as a duplicate of https://github.com/ASFHyP3/hyp3/issues/1625

**Closed by jtherrmann** 2023-07-26 23:01 UTC
Labels: enhancement
